### ISSUE TITLE
plot_unit_waveforms on windows, memmap related issue

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikewidgets#63] opened 2020-06-17 03:08 UTC
I tried to use sw.plot_unit_waveforms on windows and got the error
`File "F:\GitHub\spikeextractors\spikeextractors\baseextractor.py", line 213, in allocate_array
    arr = np.memmap(tmp_file, mode='w+', shape=shape, dtype=dtype)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\numpy\core\memmap.py", line 275, in __new__
    self.filename = filename.resolve()
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LOCALA~1\\AppData\\Local\\Temp\\tmpxut9vgik\\waveforms_0.raw'
`

But if I set memmap=False inside BaseExtractor.allocate_array it works. Sorry, if I didn't dig more in this issue.

**Comment by alejoe91** [comment] 2020-06-17 07:13
Hi @ferchaure 

Are you just running: `sw.plot_unit_waveforms(recording, sorting)`? 

Note that you can also compute waveforms with spiketoolkit (all params are exposed there)
```
wf = st.postprocessing(rec, sort, **args)
```
Among the args you can set `memmap=False`. If you run with `memmap=True` do you get the same error? I don't think it's related to `spikewidgets`, but I think we should add waveforms kwargs to the spikewidgets functions too.

**Comment by samuelgarcia** [comment] 2020-06-17 07:31
@alejoe91 : I think that 2 functions are trying to write on the same file at the same time.
We have something strange. Note that window is very very sensitive with memmap contrary to linux with is more permissive when 2 object handles the same memmap in writte acces.

**Comment by alejoe91** [comment] 2020-06-17 07:40
The only function that writes the memmap is the spiketoolkit. That's why I think that the problem is there, not in spikewidgets

**Comment by samuelgarcia** [comment] 2020-06-17 07:48
yes the problem is there be it appear in spikewidgets when matplotlib want to access the buffer.

**Comment by alejoe91** [comment] 2020-06-17 08:02
That's why I asked if the same error is there also when running from spiketoolkit

**Comment by ferchaure** [comment] 2020-06-17 10:44
Hi @alejoe91 

> Are you just running: sw.plot_unit_waveforms(recording, sorting)?

Yes

I didn't know that I could use spiketoolkit.  

>  If you run with memmap=True do you get the same error?

Yes. And if the argument is memmap=False it works fine. 

As Samuel said, the issue is related to windows been strict with memmap

**Comment by alejoe91** [comment] 2020-06-17 10:56
In spiketoolkit, can you check exactly where the error is raised? Maybe we can find a proper fix :)

**Comment by ferchaure** [comment] 2020-06-17 12:37
```
Traceback (most recent call last):
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4a39c33b94f0>", line 1, in <module>
    sw.plot_unit_waveforms(recording, si_sc, max_spikes_per_unit=100)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spikewidgets\widgets\unitwaveformswidget\unitwaveformswidget.py", line 61, in plot_unit_waveforms
    W.plot()
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spikewidgets\widgets\unitwaveformswidget\unitwaveformswidget.py", line 138, in plot
    self._do_plot()
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spikewidgets\widgets\unitwaveformswidget\unitwaveformswidget.py", line 162, in _do_plot
    save_as_features=False)[0]
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spiketoolkit\postprocessing\postprocessing_tools.py", line 167, in get_unit_waveforms
    arr = sorting.allocate_array(shape=shape, dtype=dtype, name=fname, memmap=memmap)
  File "F:\GitHub\spikeextractors\spikeextractors\baseextractor.py", line 213, in allocate_array
    arr = np.memmap(tmp_file, mode='w+', shape=shape, dtype=dtype)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\numpy\core\memmap.py", line 275, in __new__
    self.filename = filename.resolve()
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LOCALA~1\\AppData\\Local\\Temp\\tmpxut9vgik\\waveforms_0.raw'

```

**Comment by alejoe91** [comment] 2020-06-17 12:49
Thanks!

From here: 
```
File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spiketoolkit\postprocessing\postprocessing_tools.py", line 167, in get_unit_waveforms
    arr = sorting.allocate_array(shape=shape, dtype=dtype, name=fname, memmap=memmap)
  File "F:\GitHub\spikeextractors\spikeextractors\baseextractor.py", line 213, in allocate_array
    arr = np.memmap(tmp_file, mode='w+', shape=shape, dtype=dtype)
```

you can see that the program fails when creating the memmap object. So @samuelgarcia this is not related to parallel reading of the memmap file. 

Can you try to change the location of the TMP folder? You can try to set the tmp folder for the SortingExtractor only, using:

```
os.mkdir('tmp_sorting')
si_sc.set_tmp_folder('tmp_sorting)
```

This will make the sorting object save the waveforms in the folder that you created, and might solve the PermissionError. Can you test this form spiketoolkit directly?

**Comment by ferchaure** [comment] 2020-06-17 13:40
```
Traceback (most recent call last):
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-0d18a9ddc802>", line 1, in <module>
    wf = st.postprocessing.get_unit_waveforms(recording, si_sc,memmap=True)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\spiketoolkit\postprocessing\postprocessing_tools.py", line 167, in get_unit_waveforms
    arr = sorting.allocate_array(shape=shape, dtype=dtype, name=fname, memmap=memmap)
  File "F:\GitHub\spikeextractors\spikeextractors\baseextractor.py", line 213, in allocate_array
    arr = np.memmap(tmp_file, mode='w+', shape=shape, dtype=dtype)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\site-packages\numpy\core\memmap.py", line 275, in __new__
    self.filename = filename.resolve()
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tmp_sorting\\waveforms_0.raw'
```

**Comment by alejoe91** [comment] 2020-06-17 14:36
Are you running it in a notebook? Can you try to make a simple script and run it without the interactive shell? 


Does this fail too?
```
import numpy as np

arr = np.memmap('test.raw', mode='w+', shape=(100, 100), dtype='int')
```

**Comment by ferchaure** [comment] 2020-06-17 15:07
I'm not using a notebook (I tried yesterday and I got the same error)

The command works fine, I have used memmap before in windows without problems

**Comment by alejoe91** [comment] 2020-06-17 15:36
Mmm I don't see why it's failing. You can see from the error that it fails when it tries to create a new memmap object...and it's not in a different process

@samuelgarcia any ideas?

If you create a memmap object outside that function, does it throw the same error? 
```
arr = si_sc.allocate_array(name='test.raw', shape=(100,100), memmap=True, dtype='int')
```

**Comment by ferchaure** [comment] 2020-06-17 16:33
yes
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LOCALA~1\\AppData\\Local\\Temp\\tmp00xi8wb5\\test.raw'
`
The same if I set the tmp_folder.

**Comment by alejoe91** [comment] 2020-06-17 16:59
Ok, thanks for checking.

I found similar issues when the memmaped file is deleted before closing it. But that doesn't seem to be the case. In fact, `np.memmap` accepts file paths as input (https://numpy.org/devdocs/reference/generated/numpy.memmap.html)...

As soon as I have access to a windows machine I'll try to figure out why this is happening

**Comment by samuelgarcia** [comment] 2020-06-18 06:38
One total speculative scenario I can see is:

1. One recording object "rec0" create a memmap at "path0"
2. We plot this trace with matplotlib
3. We delete the rec0 object because we don't need it.
4. We create another object "rec1" at the same place "path0" (unfortunatly)

In this scenario, the "path0" is not deleted at step 3 because the matplotlib still reference the buffer, so the memmap and so the file. And then at step 4, the new object is not able to create a file at the same place.
On linux the file system make it possible but on windows this is not allowed.

**Comment by alejoe91** [comment] 2020-06-18 13:46
HI @ferchaure 

I tested this on Windows 10, miniconda3, Python 3.8, SpikeInterface 0.9.9:

```
import spikeextractors as se

rec, sort = se.example_datasets.toy_example()

arr = sort.allocate_array(memmap=True, dtype='float', shape=(100,100), name='test.raw')
```

And it creates the memmap object without errors. Can you try this snippet out?

**Comment by ferchaure** [comment] 2020-06-18 14:55
I got the error, I'm using windows 7 and Python 3.7. 
I  created a new env with python 3.8, installed SpikeInterface, run the lines and got the error again. 
But I have been doing some tests:

if tmp_file is a WindowsPath (created using the Path library) I got the error doing: 
`np.memmap(tmp_file, mode='w+', shape=(100,100), dtype='float')

but if I parse it to string like:

`np.memmap(str(tmp_file), mode='w+', shape=(100,100), dtype='float')

It works fine :smile:

**Comment by samuelgarcia** [comment] 2020-06-18 14:56
@alejoe91 : you owe me a beer.

**Comment by alejoe91** [comment] 2020-06-18 15:20
@ferchaure thanks! I'll make a PR!

And @samuelgarcia let's make it 2 eheh

**Comment by alejoe91** [comment] 2020-06-18 15:43
@ferchaure can you test with the latest spikeextractors master?

**Comment by ferchaure** [comment] 2020-06-18 16:44
It works without problems :smiley:

**Closed** 2020-06-23 12:56 UTC
